In [1]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

## 1

In [5]:
df['job_posted_date_str'] = df['job_posted_date'].apply(lambda x: x.strftime('%Y-%m-%d'))
df[['job_posted_date_str', 'job_posted_date']].head()

  job_posted_date_str     job_posted_date
0          2023-06-16 2023-06-16 13:44:15
1          2023-01-14 2023-01-14 13:18:07
2          2023-10-10 2023-10-10 13:14:55
3          2023-07-04 2023-07-04 13:01:41
4          2023-08-07 2023-08-07 14:29:36

## 2

In [8]:
from datetime import datetime
current_date = datetime.now()
df['days_since_posted'] = df['job_posted_date'].apply(lambda date: (current_date - date).days)
df[['job_posted_date', 'days_since_posted']].head()

      job_posted_date  days_since_posted
0 2023-06-16 13:44:15               1003
1 2023-01-14 13:18:07               1156
2 2023-10-10 13:14:55                887
3 2023-07-04 13:01:41                985
4 2023-08-07 14:29:36                951

## 3

In [21]:
df_filtered = df.dropna(subset=['salary_year_avg']).copy()
df_filtered['salary_category'] = df['salary_year_avg'].apply(lambda salary: 'Low' if salary < 60000  else 'Medium' if salary <= 100000 else 'High')
df_filtered[['salary_year_avg', 'salary_category']]

        salary_year_avg salary_category
28             109500.0            High
77             140000.0            High
92             120000.0            High
100            228222.0            High
109             89000.0          Medium
...                 ...             ...
785624         139216.0            High
785641         150000.0            High
785648         221875.0            High
785682         157500.0            High
785692         157500.0            High

[22003 rows x 2 columns]