In [1]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
df.pivot_table(index=['job_title_short', 'job_country'],aggfunc='size').head(10)

job_title_short   job_country
Business Analyst  Afghanistan      4
                  Albania         11
                  Algeria         21
                  Angola           1
                  Argentina      453
                  Armenia         29
                  Australia      928
                  Austria        738
                  Azerbaijan      16
                  Bahamas          5
dtype: int64

In [3]:
df.pivot_table(index='company_name', values='salary_year_avg', aggfunc=['min', 'max', 'mean'])

,min,max,mean
,salary_year_avg,salary_year_avg,salary_year_avg
company_name,,,
#twiceasnice Recruiting,61000.000000,120000.000000,77750.000000
/dev/color,125000.000000,125000.000000,125000.000000
0nward Select,92500.000000,92500.000000,92500.000000
1 Point System,137290.484375,137290.484375,137290.484375
1 Point System LLC.,170000.000000,170000.000000,170000.000000
...,...,...,...
zooplus SE,157500.000000,166000.000000,161750.000000
ztp,95000.000000,95000.000000,95000.000000
ЛАНИТ,400000.000000,400000.000000,400000.000000
Технологическая компания,280000.000000,280000.000000,280000.000000
​Illinois State Board of Education,62536.000000,62536.000000,62536.000000

In [5]:
df_DS = df[df['job_title_short'] == 'Data Scientist'] #filter for only data scientist jobs

pivot_table = df_DS.pivot_table(index=['company_name', 'job_country'], values='salary_year_avg', aggfunc='median')

filtered_pivot_table = pivot_table[pivot_table['salary_year_avg'] >200000]
filtered_pivot_table.head(10)

                                   salary_year_avg
company_name        job_country
ACT                 Sudan                 225000.0
                    United States         225000.0
Abbott              United States         204000.0
Airbnb              United States         212500.0
Airtable            Sudan                 215500.0
                    United States         233500.0
Algo Capital Group  Sudan                 325000.0
                    United States         350000.0
Amadeus Search      United States         232500.0
Analog Devices, Inc United States         375000.0